FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Copy .env.sample and rename it to .env
COPY .env.sample .env

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]